before_script:
  - apt-get update -qq && apt-get install -y -qq pandoc make texlive-latex-base texlive-fonts-recommended latex-beamer

test:
  stage: test
  script:
    - make
  except:
    - master

pages:
  stage: deploy
  script:
    - make pages
  artifacts:
    paths:
      - public
  only:
    - master
